CREATE TABLE `agencies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agencyNameAr` varchar(300) NOT NULL,
	`agencyNameEn` varchar(300),
	`agencySlug` varchar(300) NOT NULL,
	`agencyLogo` varchar(1000),
	`agencyCoverImage` varchar(1000),
	`agencyPhone` varchar(30),
	`agencyEmail` varchar(320),
	`agencyWhatsapp` varchar(30),
	`agencyWebsite` varchar(500),
	`agencyLicenseNumber` varchar(100),
	`agencyDescriptionAr` text,
	`agencyDescriptionEn` text,
	`agencyCity` varchar(200),
	`agencyCityEn` varchar(200),
	`agencyDistrict` varchar(200),
	`agencyDistrictEn` varchar(200),
	`agencyAddress` text,
	`agencyAddressEn` text,
	`agencyInstagram` varchar(500),
	`agencyTwitter` varchar(500),
	`agencyTiktok` varchar(500),
	`agencySnapchat` varchar(500),
	`agencyLinkedin` varchar(500),
	`agencyStatus` enum('active','inactive','pending') NOT NULL DEFAULT 'pending',
	`agencyIsFeatured` boolean NOT NULL DEFAULT false,
	`agencySortOrder` int NOT NULL DEFAULT 0,
	`agencyCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`agencyUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agencies_id` PRIMARY KEY(`id`),
	CONSTRAINT `agencies_agencySlug_unique` UNIQUE(`agencySlug`)
);
--> statement-breakpoint
CREATE TABLE `agents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentAgencyId` int NOT NULL,
	`agentNameAr` varchar(300) NOT NULL,
	`agentNameEn` varchar(300),
	`agentSlug` varchar(300) NOT NULL,
	`agentPhoto` varchar(1000),
	`agentPhone` varchar(30),
	`agentEmail` varchar(320),
	`agentWhatsapp` varchar(30),
	`agentTitleAr` varchar(200),
	`agentTitleEn` varchar(200),
	`agentBioAr` text,
	`agentBioEn` text,
	`agentYearsExperience` int,
	`agentSpecialties` json,
	`agentLanguages` json,
	`agentIsActive` boolean NOT NULL DEFAULT true,
	`agentSortOrder` int NOT NULL DEFAULT 0,
	`agentCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`agentUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agents_id` PRIMARY KEY(`id`),
	CONSTRAINT `agents_agentSlug_unique` UNIQUE(`agentSlug`)
);
--> statement-breakpoint
ALTER TABLE `properties` ADD `agencyId` int;--> statement-breakpoint
ALTER TABLE `properties` ADD `agentId` int;